CREATE TABLE Shared_With (
	N_E_ID		INT			NOT NULL,
    N_ID		INT			NOT NULL,
    SP_E_ID		INT			NOT NULL,
	SP_ID		INT			NOT NULL,
    P_ID		INT,
    FOREIGN KEY (N_E_ID, N_ID) REFERENCES Assist_Nurse(E_ID, N_ID),
    FOREIGN KEY (SP_E_ID, SP_ID) REFERENCES Service_Provider(E_ID, SP_ID),
	FOREIGN KEY (P_ID, N_E_ID, N_ID, SP_E_ID, SP_ID) REFERENCES  Note(P_ID, N_E_ID, N_ID, SP_E_ID, SP_ID));